"""add payment mode to expenses

Revision ID: 857859778d98
Revises: 
Create Date: 2026-09-07 16:02:45.564005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '857859778d98'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "expenses",
        sa.Column(
            "payment_mode",
            sa.String(),
            nullable=False,
            server_default="Other",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'payment_mode')
    # ### end Alembic commands ###
